### ISSUE TITLE
Dockerfile doesn't work out of the box

### ISSUE THREAD

**Issue by krumware** [stephenvolpe/JS-resume#2]
The existing dockerfile does not target the proper directories for component installs. I think the only reason it works right now is the node_modules folder is already included in the file structure.  The dockerfile should run with the node_modules folder missing.

Here are my updates that work:

```dockerfile
FROM node:8
RUN mkdir /my-app && mkdir /temp
COPY . /my-app
RUN cd /my-app && npm install -g forever nodemon && npm install
WORKDIR /my-app
EXPOSE  8081
#CMD ["npm", "start"]
CMD ["npm", "start", "--","--hostname","0.0.0.0", "--port", "8081"]
```

**Comment by stephenvolpe** [comment]
Having an issue when I try to docker pull stephenvolpe/js-resume:latest

Error response from daemon: pull access denied for stephenvolpe/js-resume, repository does not exist or may require 'docker login'

Going to try to look at it this weekend

**Comment by krumware** [comment]
You won't be able to pull it. You need to build an image with that tag. You can change the tag for your own, it's just the one I picked, per the other issues
